spring:
  config:
    import: optional:configserver:https://flux-config-server.fly.dev/

  cloud:
    config:
      username: maxvpire
      password: h(wuP}}&R8Jk1RT/0$5KBT$yw00
  application:
    name: discovery-service
