spring:
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      username: maxvpire
      password: h(wuP}}&R8Jk1RT/0$5KBT$yw00
  application:
    name: gateway-service