spring:
  config:
    import: optional:configserver:https://flux-config-server.fly.dev/
  security:
    oauth2:
      resourceserver:
        jwt:
          # Same realm as Gateway â€“ this is important
          issuer-uri: http://localhost:8080/realms/flux
  cloud:
    config:
      username: maxvpire
      password: h(wuP}}&R8Jk1RT/0$5KBT$yw00
  application:
    name: user-management-service