spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: calendar-service

google:
  calendar:
    enabled: true  # Set to true to enable Google Calendar sync
#    client-id: ${GOOGLE_CLIENT_ID}
#    client-secret: ${GOOGLE_CLIENT_SECRET}
#    redirect-uri: ${GOOGLE_REDIRECT_URI}
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    redirect-uri: ${GOOGLE_REDIRECT_URI}
    application-name: Calendar Sync App
    calendar-id: primary

zoom:
  api:
    account-id: ${ZOOM_ACCOUNT_ID}
    client-id: ${ZOOM_CLIENT_ID}
    client-secret: ${ZOOM_CLIENT_SECRET}
minio:
  endpoint: ${MINIO_ENDPOINT}
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  bucket: ${MINIO_BUCKET}